<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('produk')->insert([
            [
                'nama' => 'Bakso',
                'deskripsi' => 'Bakso adalah makanan yang terbuat dari campuran daging sapi dan tepung tapioka yang dicampur dengan bumbu-bumbu tertentu.',
                'foto' => 'produk_foto/QBSDHaPgSX5ryR4tuQfQbCwFdwnt3al3f7x343uH.jpg',
                'harga' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lontong Kikil',
                'deskripsi' => 'Lontong Kikil adalah hidangan khas dengan kikil sapi yang lezat.',
                'foto' => 'produk_foto/C5Hswe0VKhFQBVNn31wwGZtFEIge4mqZTS1R9Yin.jpg',
                'harga' => 12500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tahu Campur',
                'deskripsi' => 'Tahu Campur adalah makanan khas Indonesia dengan campuran tahu, lontong, dan kuah.',
                'foto' => 'produk_foto/Z3XfJOoIgyzZL2luo2N20325hyp2gOJFCFZTzCw1.jpg',
                'harga' => 12500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Siomay',
                'deskripsi' => 'Siomay adalah makanan khas dengan isian ikan dan disajikan dengan saus kacang.',
                'foto' => 'produk_foto/yLi4QV6kEWyN1ADJ6FGlB1RU2wp17EMzF4qavYq8.jpg',
                'harga' => 12500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mi Cawan',
                'deskripsi' => 'Mi Cawan adalah hidangan mi dengan rasa autentik dan lezat.',
                'foto' => 'produk_foto/6kLVFr4tMl2ZmxaI8ykuQy3xkz8PPDrqCEPb5wtE.png',
                'harga' => 12500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mi Sarang Burung',
                'deskripsi' => 'Mi Sarang Burung adalah hidangan unik berbentuk sarang dengan rasa nikmat.',
                'foto' => 'produk_foto/6kLVFr4tMl2ZmxaI8ykuQy3xkz8PPDrqCEPb5wtE.png',
                'harga' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sate Ayam',
                'deskripsi' => 'Sate Ayam adalah hidangan daging ayam yang ditusuk dan dibakar dengan bumbu kacang.',
                'foto' => 'produk_foto/g6XOKSH1YinZqGDYy5o7hATNmfMlVefJS01aaCjc.jpg',
                'harga' => 17500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sate Kambing 500 Tusuk + Gulai Kambing 1 Panci',
                'deskripsi' => 'Sate Kambing adalah hidangan pesta dengan jumlah yang sangat banyak serta Gule Kambing  merupakan hidangan kaya rempah untuk banyak orang.',
                'foto' => 'produk_foto/5Q2GsQoDC8C5rhYlaGOSlVDTw0ahkBgCMPj9K2RL.jpg',
                'harga' => 3750000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kambing Guling',
                'deskripsi' => 'Kambing Guling adalah menu istimewa untuk acara besar.',
                'foto' => 'produk_foto/tRWdVkvox7JRdp6GkTNHlVHdmldOtOmRU9wvoi6m.jpg',
                'harga' => 3500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Soto Mi',
                'deskripsi' => 'Soto Mi adalah soto khas dengan campuran mi dan kuah kaldu.',
                'foto' => 'produk_foto/6kLVFr4tMl2ZmxaI8ykuQy3xkz8PPDrqCEPb5wtE.png',
                'harga' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kebab',
                'deskripsi' => 'Kebab adalah makanan khas Timur Tengah yang menggugah selera.',
                'foto' => 'produk_foto/zvkLbnGY54354hRTzcodf7QdEAmdrvFLIU1UlPXx.jpg',
                'harga' => 12500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Martabak',
                'deskripsi' => 'Martabak adalah makanan manis atau gurih yang sangat populer.',
                'foto' => 'produk_foto/nb6687xhZ6yWbLKBGhzg35yOxCTwfghBtqhoWjel.jpg',
                'harga' => 40000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Soto Daging',
                'deskripsi' => 'Soto Daging adalah soto dengan irisan daging sapi.',
                'foto' => 'produk_foto/FEL8MxNkx3dhObYrNCdTczdAYKI4gsv2I00uLMms.jpg',
                'harga' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Soto Ayam',
                'deskripsi' => 'Soto Ayam adalah soto dengan ayam suwir yang lezat.',
                'foto' => 'produk_foto/5GUHzP23zVFVhIlJ29mAOLXqo5chFEqSGxR37Iso.jpg',
                'harga' => 17500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rawon',
                'deskripsi' => 'Rawon adalah sup khas Indonesia dengan kuah hitam dari kluwek.',
                'foto' => 'produk_foto/TIEEOUtifF8FOHN286gaBH5u9SBiP4geKMzoV05m.jpg',
                'harga' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pecel',
                'deskripsi' => 'Pecel adalah hidangan sayuran rebus dengan saus kacang.',
                'foto' => 'produk_foto/gKFXc0fbGW6l6LUADDrznCQrIsKAY8RDFEtZLXcr.jpg',
                'harga' => 12500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rames',
                'deskripsi' => 'Rames adalah nasi dengan berbagai lauk pauk khas Indonesia.',
                'foto' => 'produk_foto/mP3KytapmJ5IZ3yuc4qATihaO1N6ORMSCbsuyt0M.jpg',
                'harga' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lontong Gomek',
                'deskripsi' => 'Lontong Gomek adalah hidangan lontong dengan kuah santan.',
                'foto' => 'produk_foto/JHodkco2BA7vhb9zf0lxdiN6lqO0AJrRC2jV3U1D.png',
                'harga' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tomyam',
                'deskripsi' => 'Tomyam adalah sup asam pedas khas Thailand.',
                'foto' => 'produk_foto/kbZatSZ9mauTsyZTc6wt3jjRsyp7yI2hGe0igkCa.jpg',
                'harga' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Es Firdaus',
                'deskripsi' => 'Es Firdaus adalah minuman segar khas daerah.',
                'foto' => 'produk_foto/6kLVFr4tMl2ZmxaI8ykuQy3xkz8PPDrqCEPb5wtE.png',
                'harga' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bubur Ayam Jakarta',
                'deskripsi' => 'Bubur Ayam Jakarta adalah bubur ayam dengan berbagai topping.',
                'foto' => 'produk_foto/FlqGo6Tdn93wITx1kzaanZswWtgs3WxyCPMrLnuz.jpg',
                'harga' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bubur Madura',
                'deskripsi' => 'Bubur Madura adalah hidangan khas Madura dengan rasa manis.',
                'foto' => 'produk_foto/SfJuqrswoI5ei38302EdTbM4JP1d47o1VyRytz6e.jpg',
                'harga' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Coto Makassar',
                'deskripsi' => 'Coto Makassar adalah sup khas Makassar dengan daging sapi.',
                'foto' => 'produk_foto/dpnoFjRzV88K5K6rUdTomTxcEKKCdB6AKD9fnwRL.jpg',
                'harga' => 25000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Spaghetti',
                'deskripsi' => 'Spaghetti adalah pasta khas Italia dengan saus spesial.',
                'foto' => 'produk_foto/TwTylW14x6xu5Ovk1rmuLFvhr9dwohJC5nCJmGK6.jpg',
                'harga' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tami Capcay',
                'deskripsi' => 'Tami Capcay adalah capcay dengan tami yang renyah.',
                'foto' => 'produk_foto/6kLVFr4tMl2ZmxaI8ykuQy3xkz8PPDrqCEPb5wtE.png',
                'harga' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dimsum',
                'deskripsi' => 'Dimsum adalah camilan khas dengan berbagai isian lezat.',
                'foto' => 'produk_foto/OE5zdGA3no2Wd8FqWUHE8g7NPpYvA1R6Wa5NU7qm.jpg',
                'harga' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Soto Banjar',
                'deskripsi' => 'Soto Banjar adalah soto khas Banjar dengan kuah rempah.',
                'foto' => 'produk_foto/b3usnHMRT6vjUyL1rb9Pzp7zKZb6Zl3ebvXZIDAe.jpg',
                'harga' => 22000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Es Krim / Cup',
                'deskripsi' => 'Es Krim adalah dessert favorit semua orang.',
                'foto' => 'produk_foto/fASU0EPlTRoavUY2S8Z7qpxUTHeoFEXz07oM3wHR.jpg',
                'harga' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Jasuke',
                'deskripsi' => 'Jasuke adalah jagung manis dengan keju dan susu.',
                'foto' => 'produk_foto/Az815NbURMmACgoJiEP2XZPjvCQUsDSNzDmUOrrs.jpg',
                'harga' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sup Matahari',
                'deskripsi' => 'Sup Matahari adalah sup khas dengan bentuk bunga matahari.',
                'foto' => 'produk_foto/jwyM7HCI6rm99zyCR5S1kBVow3LJTVk5B1whAKpN.jpg',
                'harga' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lontong Mi',
                'deskripsi' => 'Lontong Mi adalah hidangan lontong dengan mi dan kuah.',
                'foto' => 'produk_foto/Nxtemcm3UvMc0k5ZZdaemn6nHLiQBJfzlvvxAZh5.jpg',
                'harga' => 12500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Gado-gado',
                'deskripsi' => 'Gado-gado adalah salad khas Indonesia dengan saus kacang.',
                'foto' => 'produk_foto/yzPEAlL9Iyb1akoicG0Gds8SKfjaQERZTQbRfFEh.jpg',
                'harga' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Zuppa Soup',
                'deskripsi' => 'Zuppa Soup adalah sup dengan pastry di atasnya.',
                'foto' => 'produk_foto/BpgArS1j0tHop17BLHZdY8Ok8QkWVcvFMpiHQTZe.jpg',
                'harga' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
